"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
OPTIONS = dict(
    argv_emulation=True,
    frameworks=['libavbin.dylib'],
)

setup(
    app=['poke.py'],
    data_files=['game', 'img', 'sound', 'pyglet'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)